######################################################
##                     Eureka                       ##
###################################################### 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
spec:
  selector:
    matchLabels:
      app: eureka-service
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - name: eureka-service
        image: davidepiona/eureka-microservice 
        ports:
        - containerPort: 8761
        - containerPort: 7761
######################################################
##                 Gateway & Gui                    ##
######################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: davidepiona/gateway-microservice-kube
        ports:
        - containerPort: 9999
        - containerPort: 7999
      - name: gui
        image: davidepiona/benchgui
        ports:
        - containerPort: 8080
######################################################
##                  Upload & Nginx                  ##
######################################################
# ---	
#  apiVersion: apps/v1
#  kind: Deployment
#  metadata:
#    name: upload
#  spec:
#    selector:
#      matchLabels:
#        app: upload
#    replicas: 1
#    template:
#      metadata:
#        labels:
#          app: upload
#      spec:
#       volumes:
#         - name: media
#           hostPath:
#             path: /home/davide/dev/benchmark/media
#         - name: conf
#           hostPath:
#             path: /home/davide/dev/benchmark/docker/default.conf
#       containers:
#         - name: upload
#           image: davidepiona/upload-microservice 
#           ports:
#           - containerPort: 8020
#           - containerPort: 7020
#           volumeMounts:
#             - mountPath: /opt/media
#               name: media
#         - name: nginx
#           image: davidepiona/nginx
#           ports:
#           - containerPort: 80
#           volumeMounts:
#           - mountPath: /opt/stream
#             name: media
#           - mountPath: /etc/nginx/conf.d/default.conf
#             name: conf
######################################################
##                     Registry                     ##
######################################################
---		
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: davidepiona/registry-microservice 
        ports:
        - containerPort: 8010
        - containerPort: 7010
######################################################
##                      Nginx  NO                     ##
######################################################
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
# spec:
#   selector:
#     matchLabels:
#       app: nginx
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       volumes:
#       - name: media
#         hostPath:
#           path: /home/davide/dev/benchmark/media
#       - name: conf
#         hostPath:
#           path: /home/davide/dev/benchmark/docker/default.confs
#       containers:
#       - name: nginx
#         image: davidepiona/nginx
#         ports:
#         - containerPort: 8888
#         volumeMounts:
#         - mountPath: /opt/stream
#           name: media
#         - mountPath: /etc/nginx/conf.d/default.conf
#           name: conf
######################################################
##                   Cassandra                      ##
######################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      volumes:
        - name: storage
          hostPath:
            path: /data/cassandra
      containers:
        - name: cassandra
          image: davidepiona/cassandra
          volumeMounts:
            - mountPath: /data/db
              name: storage
          ports:
          - containerPort: 9042
          env:
            - name: MAX_HEAP_SIZE
              value: 400M
            - name: HEAP_NEWSIZE
              value: 200M
            - name: disk_optimization_strategy
              value: ssd 
