server:
  port: 8070
spring:
  application:
    name: wsTest-service

test:
  ws: ws://127.0.0.1:8020/events/websocket
  path: /home/davide/dev/benchmark/wsTest/Bambino_Freddo.mp4
#management:
#  metrics:
#    export:
#      jmx:
#        step: 1s
