server:
  port: 8070
spring:
  application:
    name: wsTest-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true

# todo non so se sia corretto
test:
  ws: ws://upload-service:8020/events/websocket
  path: /opt/Bambino_Freddo.mp4