global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:9090']
  - job_name: 'spring-boot-2'
#    application_name: 'application'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["10.0.1.36:8010","10.0.1.36:8020", "10.0.1.36:9999", "10.0.1.36:8761", "10.0.1.36:8011"]
#  - job_name: 'spring-boot-1'
#    scrape_interval: 5s
#    metrics_path: '/prometheus'
#    static_configs:
#      - targets: ["192.168.1.43:8081"]
