server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
      gateway:
        routes:
        - id: upload
          uri: lb://upload-service
          predicates:
          - Path=/api/upload/**
          filters:
          - RewritePath=/api/upload/(?<segment>.*), api/upload/$\{segment}
          - name: Hystrix
            args:
              name: uploadFallback
        - id: registry
          uri: lb://registry-service
          predicates:
          - Path=/api/**
          filters:
          - RewritePath=/api/(?<segment>.*), api/$\{segment}
#          - name: Hystrix
#            args:
#              name: registryFallback
        - id: nginx
          uri: http://nginx:80
          predicates:
          - Path=/stream/**
          filters:
          - Hystrix=commandName
          - RewritePath=/stream/(?<segment>.*), stream/$\{segment}
        - id: gui
          uri: http://localhost:8080
          predicates:
          - Path=/**
hystrix:
  command:
    uploadFallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

hystrix:
  command:
    registryFallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


management:
  endpoints:
    web:
      exposure:
        include: health,info,env

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true

path:
  nginx: http://nginx:8888
  gui: http://gui:8080

