global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:9090']
  - job_name: 'spring-boot-2'
#    application_name: 'application'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["192.168.1.4:8010","192.168.1.4:8020", "192.168.1.4:9999", "192.168.1.4:8761", "192.168.1.4:8011", "eureka-service"]
#  - job_name: 'spring-boot-1'
#    scrape_interval: 5s
#    metrics_path: '/prometheus'
#    static_configs:
#      - targets: ["192.168.1.43:8081"]
