spring:
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-service
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,env

