server:
  port: 8020
management:
  endpoints:
    web:
      exposure:
        include: health,info,env

spring:
  servlet:
    multipart:
      max-file-size: 8024MB
      max-request-size: 8024MB
  application:
    name: upload-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true

upload:
  path: /opt/media
  environment: docker
