
server:
  port: 8010
#spring.data.cassandra.contact-points= cassandra
spring:
  data:
    cassandra:
      port: 9042
      keyspace-name: Movies
      schema-action: create_if_not_exists
  application:
    name: registry-service

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,env
  metrics:
    distribution:
      percentiles-histogram[http.server.requests]: true
      sla:
        http:
          server:
            requests: 1ms, 5ms



