
server:
  port: 8010
#spring.data.cassandra.contact-points= cassandra
spring:
  data:
    cassandra:
      port: 9042
      keyspace-name: Movies
      schema-action: create_if_not_exists
      contact-points:
        - localhost
  application:
    name: registry-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,env

upload:
#  path: C:/Users/Davide/IdeaProjects/benchmark/media/
  path: /home/davide/dev/benchmark/media/

