version: "3"
services:
  nginx:
    image: nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8888:80"
    volumes:
      - "C:/Users/Davide/IdeaProjects/benchmark/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "C:/Users/Davide/IdeaProjects/benchmark/media:/opt/stream"


